   /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventory_.management;

import java.awt.HeadlessException;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Lenovo
 */
public class InventoryControl extends javax.swing.JFrame {

    /**
     * Creates new form InventoryControl
     */
    public InventoryControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        edtProductId = new javax.swing.JTextField();
        edtProductName = new javax.swing.JTextField();
        edtQuantity = new javax.swing.JTextField();
        edtPrice = new javax.swing.JTextField();
        btnAdd = new rojerusan.RSMaterialButtonRectangle();
        btnUpdate = new rojerusan.RSMaterialButtonRectangle();
        btnDelete = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        btnDisplay = new rojerusan.RSMaterialButtonRectangle();
        btnBack = new rojerusan.RSMaterialButtonRectangle();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new rojerusan.RSMaterialButtonRectangle();
        edtSearch = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new rojeru_san.complementos.RSTableMetro();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edtProductId.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        edtProductId.setText("Product ID");
        edtProductId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        edtProductId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtProductIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtProductIdFocusLost(evt);
            }
        });
        jPanel2.add(edtProductId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 240, 50));

        edtProductName.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        edtProductName.setText("Product Name");
        edtProductName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        edtProductName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtProductNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtProductNameFocusLost(evt);
            }
        });
        jPanel2.add(edtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 240, 50));

        edtQuantity.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        edtQuantity.setText("Quantity");
        edtQuantity.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        edtQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtQuantityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtQuantityFocusLost(evt);
            }
        });
        edtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtQuantityActionPerformed(evt);
            }
        });
        jPanel2.add(edtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 240, 50));

        edtPrice.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        edtPrice.setText("Price");
        edtPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        edtPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtPriceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtPriceFocusLost(evt);
            }
        });
        edtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtPriceActionPerformed(evt);
            }
        });
        jPanel2.add(edtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 240, 50));

        btnAdd.setBackground(new java.awt.Color(0, 153, 255));
        btnAdd.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        btnAdd.setText("ADD");
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 150, 70));

        btnUpdate.setBackground(new java.awt.Color(0, 153, 255));
        btnUpdate.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 153)));
        btnUpdate.setText("UPDATE");
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 150, 70));

        btnDelete.setBackground(new java.awt.Color(0, 153, 255));
        btnDelete.setText("Delete");
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 150, 70));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(0, 153, 255));
        rSMaterialButtonRectangle1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rSMaterialButtonRectangle1.setText("RESET");
        rSMaterialButtonRectangle1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, 150, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 750));

        btnDisplay.setBackground(new java.awt.Color(0, 51, 255));
        btnDisplay.setText("Display");
        btnDisplay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDisplayMouseClicked(evt);
            }
        });
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });
        jPanel1.add(btnDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 630, 230, 70));

        btnBack.setBackground(new java.awt.Color(0, 51, 255));
        btnBack.setText("BACK");
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 640, 230, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventory/music-store.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 200, 210));

        btnSearch.setBackground(new java.awt.Color(0, 51, 255));
        btnSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSearch.setText("Search");
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 240, 140, 60));

        edtSearch.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        edtSearch.setText("Search Products");
        edtSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 255, 204), new java.awt.Color(0, 255, 204), new java.awt.Color(0, 0, 0)));
        edtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtSearchFocusLost(evt);
            }
        });
        edtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtSearchActionPerformed(evt);
            }
        });
        jPanel1.add(edtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 240, 50));

        jPanel3.setBackground(new java.awt.Color(51, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "INVENTORY", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Georgia", 1, 18), new java.awt.Color(255, 255, 153))); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        Table.setBackground(new java.awt.Color(204, 255, 255));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Quantity", "Price"
            }
        ));
        Table.setColorBackgoundHead(new java.awt.Color(0, 51, 255));
        Table.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        Table.setColorBordeHead(new java.awt.Color(255, 255, 255));
        Table.setColorFilasBackgound2(new java.awt.Color(0, 204, 204));
        Table.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        Table.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        Table.setColorForegroundHead(new java.awt.Color(204, 255, 255));
        Table.setFuenteFilas(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        Table.setFuenteFilasSelect(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        Table.setFuenteHead(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        Table.setGridColor(new java.awt.Color(255, 255, 255));
        Table.setRowHeight(30);
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table);
        if (Table.getColumnModel().getColumnCount() > 0) {
            Table.getColumnModel().getColumn(0).setPreferredWidth(75);
            Table.getColumnModel().getColumn(1).setPreferredWidth(200);
            Table.getColumnModel().getColumn(2).setResizable(false);
            Table.getColumnModel().getColumn(2).setPreferredWidth(75);
            Table.getColumnModel().getColumn(3).setPreferredWidth(75);
        }

        jPanel3.add(jScrollPane2);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 780, 280));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inventory/welcome-back.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 160, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtQuantityActionPerformed

    private void edtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtPriceActionPerformed

    public void DataTable(){
    
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
//        int sum=0;
//             for(int i=0;i<Table.getRowCount();i++){
//                sum=sum+Integer.parseInt(Table.getValueAt(i,3).toString());
                 
                  try {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "Rohan@2002");
            
//            Statement stmt;
//            stmt = con.createStatement();
//            String query = "TRUNCATE TABLE carttable";
//            stmt.executeUpdate(query);
            
            for(int i=0;i<Table.getRowCount();i++){
            String query5 = "update product_info set Quantity = (Quantity+VirtualQuantity) where (Quantity > 0) || (VirtualQuantity >0)";
            java.sql.PreparedStatement pstmt = con.prepareStatement(query5);
            pstmt.executeUpdate();
            
            }
            
      
            dispose();
               
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            //e.printStackTrace();
        }
                 
                 
        
//             
//             MessageFormat header =new MessageFormat("Invoice Print");
//         MessageFormat footer =new MessageFormat("Page");
//        try {
//            Table.print(JTable.PrintMode.FIT_WIDTH, header, footer);
//        
//            
//        } catch (PrinterException ex) {
//            Logger.getLogger(InventoryControl.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        return 0;
    
    }
    
    
    
    private void btnDisplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDisplayMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        
        model.setRowCount(0);
        
        try {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "Rohan@2002");

            Statement stmt = con.createStatement();
            String query = "select * from product_info";
            try (ResultSet rs = stmt.executeQuery(query)) {
                while (rs.next()) {
                    String id = rs.getString("ProductID");
                    String name = rs.getString("ProductName");
                    String qun = rs.getString("Quantity");
                    String price = rs.getString("Price");
                    
                    model.addRow(new Object[] {id,name,qun,price});
                }
                //stmt.close();
                //con.close();
//                
//                int sum=0;
//             for(int i=0;i<Table.getRowCount();i++)
//             {
//                sum=sum+Integer.parseInt(Table.getValueAt(i,3).toString());
//             }
             
//             MessageFormat header =new MessageFormat("Invoice Print");
//         MessageFormat footer =new MessageFormat("Page");
//        try {
//            Table.print(JTable.PrintMode.FIT_WIDTH, header, footer);
//        
//            
//        } catch (PrinterException ex) {
//            Logger.getLogger(InventoryControl.class.getName()).log(Level.SEVERE, null, ex);
//        }
//             
             
             /////////
                
            }
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            //e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_btnDisplayMouseClicked

    private void edtProductIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtProductIdFocusGained
        // TODO add your handling code here:
        if(edtProductId.getText().equals("Product ID")){
            
            edtProductId.setText("");
        }
        
    }//GEN-LAST:event_edtProductIdFocusGained

    private void edtProductIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtProductIdFocusLost
        // TODO add your handling code here:
         if(edtProductId.getText().equals("")){
            
            edtProductId.setText("Product ID");
        }
        
        
    }//GEN-LAST:event_edtProductIdFocusLost

    private void edtProductNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtProductNameFocusGained
        // TODO add your handling code here:
        if(edtProductName.getText().equals("Product Name")){
            
            edtProductName.setText("");
        }
        
    }//GEN-LAST:event_edtProductNameFocusGained

    private void edtProductNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtProductNameFocusLost
        // TODO add your handling code here:
        
        if(edtProductName.getText().equals("")){
            
            edtProductName.setText("Product Name");
        }
    }//GEN-LAST:event_edtProductNameFocusLost

    private void edtQuantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtQuantityFocusGained
        // TODO add your handling code here:
        if(edtQuantity.getText().equals("Quantity")){
            
            edtQuantity.setText("");
        }
    }//GEN-LAST:event_edtQuantityFocusGained

    private void edtQuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtQuantityFocusLost
        // TODO add your handling code here:
        if(edtQuantity.getText().equals("")){
            
            edtQuantity.setText("Quantity");
        }
    }//GEN-LAST:event_edtQuantityFocusLost

    private void edtPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtPriceFocusGained
        // TODO add your handling code here:
         if(edtPrice.getText().equals("Price")){
            
            edtPrice.setText("");
        }
        
    }//GEN-LAST:event_edtPriceFocusGained

    private void edtPriceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtPriceFocusLost
        // TODO add your handling code here:
         if(edtPrice.getText().equals("")){
            
            edtPrice.setText("Price");
        }
    }//GEN-LAST:event_edtPriceFocusLost

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
       
        String ProductID = edtProductId.getText();
        String ProductName = edtProductName.getText();
        String Quantity = edtQuantity.getText();
        String Price = edtPrice.getText();
        
        int ID = Integer.parseInt(ProductID);
        int Quan = Integer.parseInt(Quantity);
        int Pri = Integer.parseInt(Price);
        
        if(edtProductId.getText().equals("") || edtProductName.getText().equals("")|| edtQuantity.getText().equals("")|| edtPrice.getText().equals("")){
                 JOptionPane.showMessageDialog(this, "Plese Enter All Details");
        }
        
        else{
        try{
             Class.forName("com.mysql.cj.jdbc.Driver");
             Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement","root","Rohan@2002");
             Statement smt3=con.createStatement();
             int i = 0;
             String query = "insert into product_info values('"+ID+"','"+ProductName+"','"+Quan+"','"+Pri+"','"+i+"')";
 
               int success = smt3.executeUpdate(query);
                            if(success==1)
                            {
                                JOptionPane.showMessageDialog(this, "Product Successfully Added ");
                                
                                    String data[ ] = {ProductID,ProductName,Quantity,Price};
                                    DefaultTableModel tblmodel = (DefaultTableModel)Table.getModel();
                                    tblmodel.addRow(data);
                                    edtProductId.setText("Product ID");
                                    edtProductName.setText("");
                                    edtQuantity.setText("");
                                    edtPrice.setText("");
                              
                            }
                            else
                            {

                                JOptionPane.showMessageDialog(this, "Problem in Saving. Retry");
                            }
                            
        }

            catch(HeadlessException | ClassNotFoundException | SQLException e){
                
             JOptionPane.showMessageDialog(this, e.getMessage());
            }

        
        }
        
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        Dashboard Back = new Dashboard();
        Back.show();
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel tblmodel = (DefaultTableModel)Table.getModel();
        
        String tblProductID = tblmodel.getValueAt(Table.getSelectedRow(),0).toString();
        String tblProductName = tblmodel.getValueAt(Table.getSelectedRow(),1).toString();
        String tblQuantity = tblmodel.getValueAt(Table.getSelectedRow(),2).toString();
        String tblPrice = tblmodel.getValueAt(Table.getSelectedRow(),3).toString();
        
        
        edtProductId.setText(tblProductID);
        edtProductName.setText(tblProductName);
        edtQuantity.setText(tblQuantity);
        edtPrice.setText(tblPrice);
        
    }//GEN-LAST:event_TableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblmodel = (DefaultTableModel)Table.getModel();
        
        if(Table.getSelectedRow() != 1 || Table.getSelectedRow()== 1){
            
        try{
        
        String ProductID = edtProductId.getText();
        String ProductName = edtProductName.getText();
        String Quantity = edtQuantity.getText();
        String Price = edtPrice.getText();
        
        int ID = Integer.parseInt(ProductID);
        int Quan = Integer.parseInt(Quantity);
        int Pri = Integer.parseInt(Price);
        
        
  
        
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement","root","Rohan@2002");
//        Statement smt2 = con.createStatement();
        
      // String query2 = "update product_details SET Product Name = '"+ProductName+"',Quantity = '"+Quan+"',Price = '"+Pri+"' where Product ID = '"+ID+"' ";
        String query2 = "update product_info set ProductName = ?,Quantity = ?,Price = ? where ProductID = ?";
       //        + "WHERE Product ID = '"+ID+"' ";
        PreparedStatement pstmt = con.prepareStatement(query2);
       
        pstmt.setString(1,ProductName);
        pstmt.setInt(2, Quan);
        pstmt.setInt(3, Pri);
        pstmt.setInt(4, ID);
       

//          PreparedStatement statement =con.prepareStatement(query2);   
//          statement.executeUpdate();


//        
        int success = pstmt.executeUpdate();
        
//        int success = smt2.executeUpdate(query2);
        
        if(success == 1){
            JOptionPane.showMessageDialog(this, "Product Updated Successfully ");
        }else{
        
            JOptionPane.showMessageDialog(this, "Problem in Updating ,Retry ");
        }
      
//         String query2 = "UPDATE product_details SET Product Name=?, Quantity=?, Price=? where ProductID"+ProductID; 
//         PreparedStatement pst = con.prepareStatement(query2);
//         
//         pst.setString(ID, ProductName);
//         pst.setString(ID, Quantity);
//         pst.setString(ID, Price);
//         
//         pst.executeUpdate();

        tblmodel.setValueAt(ID, Table.getSelectedRow(), 0);
        tblmodel.setValueAt(ProductName,Table.getSelectedRow() , 1);
        tblmodel.setValueAt(Quan,Table.getSelectedRow() , 2);
        tblmodel.setValueAt(Pri,Table.getSelectedRow() , 3);    
            
        }
        
        
        
        catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }    
        
      
            
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblmodel = (DefaultTableModel)Table.getModel();
        
        String ProductID = edtProductId.getText();
        int ID = Integer.parseInt(ProductID);
        try{
        
            
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(InventoryControl.class.getName()).log(Level.SEVERE, null, ex);
            }
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement","root","Rohan@2002");
//            Statement smt4=con.createStatement();
            String query4 = "delete from product_info where ProductID = ?";
            PreparedStatement pstmt = con.prepareStatement(query4);
            pstmt.setInt(1, ID);
            pstmt.executeUpdate(); 
            
       
            
//            ps.setString(1,ProductID);
//            pstmt.executeUpdate();
            
            
            
            
        if(Table.getSelectedRowCount() == 1 || Table.getSelectedRowCount() > 1){
            tblmodel.removeRow(Table.getSelectedRow());

        }
        
        else{
            if(Table.getSelectedRowCount() == 0){
                 JOptionPane.showMessageDialog(this, "Table Is Empty");
            }
            else{
                 JOptionPane.showMessageDialog(this, "Plese Select Single Row For Delete");
            }
            
        }
        
        
        }
        catch(SQLException e){
        
            JOptionPane.showMessageDialog(null,e);
        }
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        
//        String query = edtSearch.getText();
//        filter(query);
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void edtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtSearchActionPerformed
        // TODO add your handling code here:
        
//        String query = edtSearch.getText();
//        filter(query);
        
    }//GEN-LAST:event_edtSearchActionPerformed

    public void filter(String query){
        DefaultTableModel tblmodel = (DefaultTableModel)Table.getModel();
        
        TableRowSorter<DefaultTableModel> search = new TableRowSorter<>(tblmodel);
        Table.setRowSorter(search);
      
        search.setRowFilter(RowFilter.regexFilter(query)) ;
                
    }
    
    
    private void edtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtSearchFocusGained
        // TODO add your handling code here:
        if(edtSearch.getText().equals("Search Products")){
            
            edtSearch.setText("");
        }
        
        
    }//GEN-LAST:event_edtSearchFocusGained

    private void edtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtSearchFocusLost
        // TODO add your handling code here:
        
        if(edtSearch.getText().equals("")){
            
            edtSearch.setText("Search Products");
        }
        
    }//GEN-LAST:event_edtSearchFocusLost

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        String query = edtSearch.getText();
        filter(query);
        
    }//GEN-LAST:event_btnSearchMouseClicked

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        // TODO add your handling code here:
        
        edtProductId.setText("Product ID");
        edtProductName.setText("Product Name");
        edtQuantity.setText("Quantity");
        edtPrice.setText("Price");
        
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InventoryControl().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSTableMetro Table;
    private rojerusan.RSMaterialButtonRectangle btnAdd;
    private rojerusan.RSMaterialButtonRectangle btnBack;
    private rojerusan.RSMaterialButtonRectangle btnDelete;
    private rojerusan.RSMaterialButtonRectangle btnDisplay;
    private rojerusan.RSMaterialButtonRectangle btnSearch;
    private rojerusan.RSMaterialButtonRectangle btnUpdate;
    private javax.swing.JTextField edtPrice;
    private javax.swing.JTextField edtProductId;
    private javax.swing.JTextField edtProductName;
    private javax.swing.JTextField edtQuantity;
    private javax.swing.JTextField edtSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    // End of variables declaration//GEN-END:variables
}
