

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventory_.management;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author Lenovo
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        edtUsername = new javax.swing.JTextField();
        edtPassword = new javax.swing.JPasswordField();
        btnReset = new rojerusan.RSMaterialButtonRectangle();
        btnLogin = new rojerusan.RSMaterialButtonRectangle();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NewImages/retailer (1).png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NewImages/seller (5).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 280, 300));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Retailer Login");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 280, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 510));

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edtUsername.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        edtUsername.setText("Enter Username"); // NOI18N
        edtUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        edtUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        edtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtUsernameFocusLost(evt);
            }
        });
        edtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtUsernameActionPerformed(evt);
            }
        });
        jPanel2.add(edtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 310, 50));

        edtPassword.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        edtPassword.setText("Password");
        edtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));
        edtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtPasswordFocusLost(evt);
            }
        });
        edtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(edtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 310, 50));

        btnReset.setBackground(new java.awt.Color(0, 153, 153));
        btnReset.setText("Reset");
        btnReset.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 140, 60));

        btnLogin.setBackground(new java.awt.Color(0, 153, 153));
        btnLogin.setText("Login");
        btnLogin.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 150, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 520, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void edtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtUsernameActionPerformed

    private void edtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtUsernameFocusGained
        // TODO add your handling code here:
        
        if(edtUsername.getText().equals("Enter Username")){
            
            edtUsername.setText("");
        }
        
    }//GEN-LAST:event_edtUsernameFocusGained

    private void edtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtUsernameFocusLost
        // TODO add your handling code here:
       
        if(edtUsername.getText().equals("")){
            
            edtUsername.setText("Enter Username");
        } 
        
    }//GEN-LAST:event_edtUsernameFocusLost

    private void edtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtPasswordFocusGained
        // TODO add your handling code here:
        
        if(edtPassword.getText().equals("Password")){
            
            edtPassword.setText("");
        }
    }//GEN-LAST:event_edtPasswordFocusGained

    private void edtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtPasswordFocusLost
        // TODO add your handling code here:
        
         if(edtPassword.getText().equals("")){
            
            edtPassword.setText("Password");
        }
    }//GEN-LAST:event_edtPasswordFocusLost

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        
  
        
        try{
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "Rohan@2002");
            
            String username = edtUsername.getText();
            String password = edtPassword.getText();
            
            Statement st = con.createStatement();
            String query = "select * from loginc_credentials where username = '"+username+"' and password = '"+password+"'";
            ResultSet rs = st.executeQuery(query);
            

            
            if(rs.next()){
            
//            JOptionPane.showMessageDialog(null, "Login Sucessfull");
            Dashboard dashboard = new Dashboard();
            dashboard.show();
            dispose();
            
            }
            
//            if(edtUsername.getText().equals("") || edtPassword.getText().equals(""))
//            {
//            JOptionPane.showMessageDialog(null, "Please Enter The Username And Password");
//            }
            
            else{
                JOptionPane.showMessageDialog(null, "Username or Password is wrong");
            }
            
            
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
        
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        
        edtUsername.setText("Enter Username");
        edtPassword.setText("********");
    }//GEN-LAST:event_btnResetActionPerformed

    private void edtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtPasswordActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_edtPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btnLogin;
    private rojerusan.RSMaterialButtonRectangle btnReset;
    private javax.swing.JPasswordField edtPassword;
    private javax.swing.JTextField edtUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
