/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventory_.management;

//import inventory_.management.Count.countRows;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
//import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
//import javax.swing.table.DefaultTableModel;
//import payments.CountCustomerID;


/**
 *
 * @author Lenovo
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
//        DateShow.Date();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        edtCusName = new javax.swing.JTextField();
        edtMakePayment = new rojerusan.RSMaterialButtonRectangle();
        btnCancelPayment = new rojerusan.RSMaterialButtonRectangle();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edtCusID = new javax.swing.JLabel();
        edtTotAmt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 153, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/purchase/payment-method.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 270, 290));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 45)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("PayMent");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 210, 100));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 550));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        edtCusName.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        edtCusName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 153, 153)));
        edtCusName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                edtCusNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                edtCusNameFocusLost(evt);
            }
        });
        edtCusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCusNameActionPerformed(evt);
            }
        });
        jPanel3.add(edtCusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 280, 50));

        edtMakePayment.setBackground(new java.awt.Color(0, 153, 153));
        edtMakePayment.setText("MAKE PayMent");
        edtMakePayment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        edtMakePayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtMakePaymentActionPerformed(evt);
            }
        });
        jPanel3.add(edtMakePayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 220, -1));

        btnCancelPayment.setBackground(new java.awt.Color(0, 153, 153));
        btnCancelPayment.setText("Cancel Payment");
        btnCancelPayment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelPaymentActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancelPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 220, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Customer ID");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 170, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Customer Name");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 200, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Total Amount");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 170, 50));

        edtCusID.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        edtCusID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 153, 153)));
        jPanel3.add(edtCusID, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 280, 50));

        edtTotAmt.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        edtTotAmt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 153, 153)));
        jPanel3.add(edtTotAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 280, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 620, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void btnCancelPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelPaymentActionPerformed
        // TODO add your handling code here:
        
//         DefaultTableModel model = (DefaultTableModel) Table.getModel();
        
            try {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "Rohan@2002");
            
            Statement stmt;
            stmt = con.createStatement();
            String query = "TRUNCATE TABLE carttable";
            stmt.executeUpdate(query);
            
            String query4 = "update product_info set Quantity = (Quantity+VirtualQuantity) where (Quantity >= 0) or (VirtualQuantity > 0)";
            java.sql.PreparedStatement pst3 = con.prepareStatement(query4);
            pst3.executeUpdate();
            
            String query5 = "update product_info set VirtualQuantity = 0 where VirtualQuantity > 0";
            java.sql.PreparedStatement pst4 = con.prepareStatement(query5);
            pst4.executeUpdate();
            
      
            dispose();
               
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            //e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnCancelPaymentActionPerformed

    private void edtMakePaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtMakePaymentActionPerformed
        // TODO add your handling code here:
        
        
        setData();
//        Rowcnt();
        
    try {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "Rohan@2002");
            
            
            String query3 = "update product_info set VirtualQuantity = 0 where (VirtualQuantity > 0)";
            java.sql.PreparedStatement pst2 = con.prepareStatement(query3);
            pst2.executeUpdate();
            
            ////////////////////////////////////////
            
            Statement stmt1;
            stmt1 = con.createStatement();
            String query4 = "INSERT INTO prodpurchase(ProdID,ProdName,ProdPrice,Quantity,Amount) SELECT ProdID,ProdName,ProdPrice,Quantity,Amount FROM carttable ";
            stmt1.executeUpdate(query4);

            
            
            
            
            
            
            ///////////////////////////////////////
            Statement stmt;
            stmt = con.createStatement();
            String query2 = "TRUNCATE TABLE carttable";
            stmt.executeUpdate(query2);
            
            dispose();
               
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            //e.printStackTrace();
        }


        

    }//GEN-LAST:event_edtMakePaymentActionPerformed

    private void edtCusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCusNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCusNameActionPerformed

    private void edtCusNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCusNameFocusGained
        // TODO add your handling code here:
//        if(edtCusName.getText().equals("      Customer Name")){
//            
//            edtCusName.setText("");
//        }
        
    }//GEN-LAST:event_edtCusNameFocusGained

    private void edtCusNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_edtCusNameFocusLost
        // TODO add your handling code here:
//        if(edtCusName.getText().equals("")){
//            
//            edtCusName.setText("      Customer Name");
//        }
    }//GEN-LAST:event_edtCusNameFocusLost

    
    public void setData(){
        
        
        Payment DateShow = new Payment();
        String data = DateShow.Date();
        
        String CusID = edtCusID.getText();
        String CusName = edtCusName.getText();
        String Amount = edtTotAmt.getText();
        
        int ID = Integer.parseInt(CusID);
        int AMOUNT = Integer.parseInt(Amount);
//        String ProdTYcnt ;
        
         try {
            Class.forName("java.sql.DriverManager");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "Rohan@2002");
            Statement smt3=con.createStatement();
            
            ////////////////////
            
            
        Statement st = con.createStatement();    
        String query4 = "SELECT Count(*) from carttable";
        ResultSet rs3 = st.executeQuery(query4);
        rs3.next();
        int cartRowcnt = rs3.getInt(1);
        String j = Integer.toString(cartRowcnt);
            
//            (CustomerID,CustomerName,TotalAmount,Date)
            
            ///////////////////
            String query = "insert into customerpurchase values('"+ID+"','"+CusName+"','"+AMOUNT+"','"+data+"','"+j+"')";
            smt3.executeUpdate(query);
            
            
            } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            //e.printStackTrace();
        }
    
    
    }
    
    public int CountCustomerID_TotalAMOUNT(){
        
        try {
        Class.forName("java.sql.DriverManager");
        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "Rohan@2002");
        Statement st = con.createStatement(); 
        
        String query = " SELECT Count(*) from customerpurchase";
        ResultSet rs = st.executeQuery(query);
        rs.next();
        int count = rs.getInt(1);
        String i = Integer.toString(count+1);
        
        edtCusID.setText(i);
        
        String query2 = " SELECT SUM(Amount) from carttable where Amount >= 0";
        ResultSet rs2 = st.executeQuery(query2);
        rs2.next();
        int Amount = rs2.getInt(1);
        
        String total = Integer.toString(Amount);
        edtTotAmt.setText(total);
//        edtTotAmts.setText(total);

        
    


        
        
        
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            //e.printStackTrace();
        }
    
        
       return 0; 
    }
    
    
    public String Date(){
    
        
        DateTimeFormatter dates = DateTimeFormatter.ofPattern("yyyy//MM/dd");
        LocalDateTime now = LocalDateTime.now();
//        DateShow.setText(dates.format(now));
        String data = dates.format(now);
        return data;
    }
    
    
    public int Rowcnt(){
        
        
        try {
            
         
            
        Class.forName("java.sql.DriverManager");
        Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/inventorymanagement?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "Rohan@2002");
        Statement st = con.createStatement(); 
        
        String query3 = "SELECT Count(*) from carttable";
        ResultSet rs3 = st.executeQuery(query3);
        rs3.next();
        int cartRowcnt = rs3.getInt(1);
        String j = Integer.toString(cartRowcnt);
        
        
        String query4 = "update customerpurchase TypeObjCnt = ? where CustomerID = ?";
        java.sql.PreparedStatement pstmt = con.prepareStatement(query4);
       
        pstmt.setString(1,j);
        pstmt.setString(2,edtCusID.getText());
        
        
         } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
            //e.printStackTrace();
        }
        
        
        return 0;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Payment().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btnCancelPayment;
    private javax.swing.JLabel edtCusID;
    private javax.swing.JTextField edtCusName;
    private rojerusan.RSMaterialButtonRectangle edtMakePayment;
    private javax.swing.JLabel edtTotAmt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

  
//    private int countRow() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }
}
